sonar.projectKey=Jylhis_Makework
sonar.organization=jylhis

# This is the name displayed in the SonarCloud UI.
sonar.projectName=makework

# Path is relative to the sonar-project.properties file.
sonar.sources=cmd,internal
sonar.exclusions=vendor/**,test-space/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Go coverage
sonar.go.coverage.reportPaths=coverage.out

# golangci-lint report
sonar.go.golangci-lint.reportPaths=golangci-report.xml
